/** @type {import('tailwindcss').Config} */
// Tokens extraídos do export do Google Stitch (kawaii_retro_shift_system/DESIGN.md
// + os tailwind.config inline de cada tela). Este é o contrato visual: não alterar.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1a1c1b",
        "secondary-fixed-dim": "#e3bcce",
        "inverse-primary": "#abcec1",
        "on-background": "#1a1c1b",
        "primary-fixed-dim": "#abcec1",
        background: "#faf9f7",
        "surface-variant": "#e3e2e0",
        "on-surface-variant": "#414845",
        "on-primary-fixed": "#002018",
        "inverse-surface": "#2f3130",
        "secondary-fixed": "#ffd8e9",
        "on-secondary-fixed-variant": "#5b3e4d",
        "surface-dim": "#dadad8",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2e0",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#2d4d43",
        tertiary: "#665e3c",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        surface: "#faf9f7",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "surface-bright": "#faf9f7",
        "outline-variant": "#c1c8c4",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f1ef",
        "surface-container-low": "#f4f4f1",
        outline: "#717975",
        secondary: "#745665",
        primary: "#44655a",
        "on-tertiary-container": "#6d6542",
        "primary-fixed": "#c6eadc",
        "primary-container": "#c7ebdd",
        "surface-container": "#eeeeec",
        "tertiary-container": "#efe3b8",
        "on-secondary-fixed": "#2b1421",
        "on-tertiary-fixed-variant": "#4e4727",
        "on-tertiary-fixed": "#211b02",
        "secondary-container": "#fdd5e7",
        "tertiary-fixed": "#eee3b7",
        "surface-container-high": "#e8e8e6",
        "surface-tint": "#44655a",
        "on-secondary-container": "#795a69",
        "on-primary-container": "#4b6b60",
        "tertiary-fixed-dim": "#d1c79d",
        // Brand colors (tela "preencher plantão")
        "brand-mint": "#98FFD1",
        "brand-pink": "#FFA6C9",
        "brand-yellow": "#FFF59D",
        "brand-orange": "#FF8A65",
        "brand-offwhite": "#FFFDF7",
        "brand-dark": "#2D2D2D",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "12px",
        "container-padding": "16px",
        unit: "4px",
        "offset-shadow": "4px",
      },
      fontFamily: {
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Quicksand", "sans-serif"],
        "body-md": ["Quicksand", "sans-serif"],
        "pixel-data": ["Space Mono", "monospace"],
        "label-caps": ["Space Mono", "monospace"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-1px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "pixel-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "700" }],
      },
      borderWidth: {
        3: "3px",
      },
      boxShadow: {
        brutal: "4px 4px 0px 0px #1a1c1b",
        "brutal-active": "0px 0px 0px 0px #1a1c1b",
        "brutal-nav": "4px 4px 0px 0px rgba(26,28,27,1)",
      },
      animation: {
        "pop-in": "popIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-subtle": "pulseSubtle 2s infinite ease-in-out",
        "float-1": "floatAnim 6s ease-in-out infinite",
        "float-2": "floatAnim 8s ease-in-out infinite reverse",
        sparkle: "sparkleAnim 1.5s infinite",
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
      },
      keyframes: {
        popIn: {
          "0%": { opacity: "0", transform: "translateY(20px) scale(0.95)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        pulseSubtle: {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.02)" },
        },
        floatAnim: {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-15px) rotate(10deg)" },
        },
        sparkleAnim: {
          "0%, 100%": { opacity: "0", transform: "scale(0.5)" },
          "50%": { opacity: "1", transform: "scale(1.2)" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
